apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-access
spec:
  podSelector:
    matchLabels:
      app: spring-boot-app
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: postgres
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
