apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: 1
  serviceName: kafka
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: kafka # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: kafka # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits: # limit of 0.5 cpu and 512MiB of memory
              memory: "512Mi"
              cpu: "500m"
          # imagePullPolicy: Always
          ports:
            - containerPort: 9092
              name: kafka-0
            - containerPort: 9093
              name: kafka-1
            - containerPort: 9094
              name: kafka-2
          env:
            - name: MY_METADATA_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: STAS_DELAY
              value: "120"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181 # zookeeper-2.zookeeper.default.svc.cluster.local
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INSIDE://$(MY_POD_IP):9092"
            - name: KAFKA_LISTENERS
              value: "INSIDE://$(MY_POD_IP):9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INSIDE:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INSIDE"