apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-postgres
  template:
    metadata:
      labels:
        app: search-postgres
    spec:
      containers:
        - name: search-postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env: # Setting Enviornmental Variables
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: search-postgres-credentials # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: search-postgres-credentials
                  key: postgres_password

---
apiVersion: v1
kind: Service
metadata:
  name: search-postgres
spec:
    selector:
        app: search-postgres
    ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432