apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  selector:
    matchLabels:
      app: admin-service
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: osamahossiny/admin-service
          ports:
            - containerPort: 8083
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: admin-postgres-configmap  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: admin-postgres-configmap
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: admin-postgres-credentials # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: admin-postgres-credentials
                  key: postgres_password

---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    name: admin-service
spec:
  type: NodePort
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30003